from setuptools import setup, find_packages

setup(
    name="cary_package",
    version="0.0.1",
    author="carycha",
    license='MIT License',
    description="自己用的小工具",
    packages=find_packages(),
    py_modules=['cary_package'],
    package_data={'cary_package': ['static/jieba_dict/*.*']},
    include_package_data=True,
    install_requires=[
        # 'jieba',
        'jieba-fast>=0.53',
        'pyahocorasick>=2.1.0',
        'ndjson>=0.3.1',
        'elasticsearch>=8.13.0',
        'redis>=5.2.1',
        'pymysql>=1.1.1',
        'pandas>=2.2.3',
        'google>=3.0.0',
        'unicodedata2>=15.1.0',
        'requests>=2.32.3',
        'scikit-learn>=1.6.1',
        'httpx>=0.28.1',
        'numpy>=2.2.2',
        'scipy>=1.15.1',
        'beautifulsoup4>=4.12.3',
    ],
)
